version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: dux_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: dux_user
      POSTGRES_PASSWORD: dux_pass
      POSTGRES_DB: dux_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
